CREATE TABLE members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_number   VARCHAR(20)  NOT NULL UNIQUE,
    full_name       VARCHAR(150) NOT NULL,
    phone_number    VARCHAR(15)  NOT NULL UNIQUE,
    national_id     VARCHAR(20)  NOT NULL UNIQUE,
    joined_date     DATE         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contributions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT       NOT NULL REFERENCES members(id),
    amount          NUMERIC(12,2) NOT NULL,
    contributed_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reference       VARCHAR(50)
);

CREATE TABLE loans (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           BIGINT       NOT NULL REFERENCES members(id),
    requested_amount    NUMERIC(12,2) NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    decision_reason     VARCHAR(255),
    applied_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at          TIMESTAMP
);

CREATE INDEX idx_contributions_member ON contributions(member_id);
CREATE INDEX idx_loans_member ON loans(member_id);
